apiVersion: batch/v1
kind: Job
metadata:
  name: valkey-operator-installer
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: valkey-operator-installer
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - |
              echo "Applying Valkey Operator install.yaml"
              kubectl apply -f /install/install.yaml
          volumeMounts:
            - name: install
              mountPath: /install
      volumes:
        - name: install
          configMap:
            name: valkey-operator-installer