image:
  repository: int-harbor.int.taqniat.ae/valkey/valkey
  tag: 9-alpine3.23

replicas: 1

nodes: 3

persistence:
  enabled: true
  size: 10Gi
  storageClass: vsphere-db

auth:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi