apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey-cluster.fullname" . }}
  labels:
    {{- include "valkey-cluster.labels" . | nindent 4 }}

spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ include "valkey-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: valkey

  ports:
    - name: valkey
      port: {{ .Values.service.port }}
      targetPort: 6379
      nodePort: {{ .Values.service.nodePort }}
