apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey-cluster.fullname" . }}-headless
  labels:
    {{- include "valkey-cluster.labels" . | nindent 4 }}

spec:
  clusterIP: None

  selector:
    app.kubernetes.io/name: {{ include "valkey-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: valkey

  ports:
    - name: valkey
      port: {{ .Values.service.port }}
      targetPort: valkey